### ISSUE TITLE
like (save) existing playlist to account

### ISSUE THREAD

**Issue by RPB543** [Demsley1/musit_2#5]

**Comment by Demsley1** [comment]
## Description:

- Create vote model and table
- Link vote table to User and Playlist
- Add JS to handle button click for like button
- Attach vote model to include in user, and playlist routes

**Comment by labchild** [comment]
- [ ] created vote model
- [ ] linked votes to playlist and users as through table
- [ ] added click handler to frontend
- [ ] added votes to routes & api routes
